name: Electron Forge Release

on:
  workflow_run:
    workflows: ["Build Electron App"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts-windows
          path: out/make/windows
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts-linux
          path: out/make/linux
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts-macos
          path: out/make/macos

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/**/*
